version: '3.7'
services:
    postgres:
        image: postgres:10.5
        restart: always
        env_file:
          - db.env
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          - ./data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
